logging:
  level:
    org:
      springframework: INFO
odata:
  jpa:
    punit_name: _s_t_s___b_u_s___v_1_6_
    root_packages: com.apps.sts
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;MODE=LEGACY;INIT=RUNSCRIPT FROM 'classpath:myscript.sql';;
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: false
  servlet:
    multipart:
      enabled: false

eclipselink:
  ddl:
    auto:
      create:
        delete: true

h2:
  console.enabled: true